### ISSUE TITLE
Small PG card affiche le solde de tout le monde sur l'historique général???

### ISSUE THREAD

**Issue by Teiwin** [REZAL-AM-KIN/kfet#28]
randomiser les couleurs en fonction de la bucque ?

laisser vert

en tout cas, pourquoi on afficherait sur l'historique général les pg en négat's en rouge???

**Comment by Teiwin** [comment]
#22

**Comment by peufgeul** [comment]
![Capture d’écran du 2024-05-11 21-58-42](https://github.com/REZAL-AM-KIN/kfet/assets/98660368/db1185ee-02d7-4869-baa7-f5908816c298)

**Comment by peufgeul** [comment]
PR #27
